### ISSUE TITLE
Encoding error with V3 onions

### ISSUE THREAD

**Issue by GIJack** [k4m4/onioff#3]
[+] Tor running normally
encoding error : input conversion failed due to input error, bytes 0x98 0x83 0x20 0x59
encoding error : input conversion failed due to input error, bytes 0x98 0x83 0x20 0x59
encoding error : input conversion failed due to input error, bytes 0x98 0x83 0x20 0x59

**Comment by k4m4** [comment]
Hi there. Can you please provide some more information such as the addresses that you used? Thanks!
